/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

import java.util.ArrayList;
import java.util.List;
import controlador.Usuario;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;

/**
 *
 * @author danie
 */
public class biblioteca extends javax.swing.JFrame {
List<Usuario> listaUsu = new ArrayList<>(); 
        ArrayList<String> entrada = new  ArrayList<>();
        ArrayList<String> supo = new  ArrayList<>();
    /**
     * Creates new form biblioteca
     */
    public biblioteca() {
        initComponents();
    }
    
    public biblioteca(List<Usuario> listaUsu, List<String> entrada, List<String> supo ) {
        initComponents();
        
        this.listaUsu = listaUsu;
        this.entrada = (ArrayList<String>) entrada;
        this.supo = (ArrayList<String>) supo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ptsair = new javax.swing.JLabel();
        biblio1 = new javax.swing.JLabel();
        biblio2 = new javax.swing.JLabel();
        biblio3 = new javax.swing.JLabel();
        biblio4 = new javax.swing.JLabel();
        redimensionar = new javax.swing.JButton();
        ptfechar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        sim = new javax.swing.JButton();
        nao = new javax.swing.JButton();
        botunder = new javax.swing.JButton();
        botcup = new javax.swing.JButton();
        botamong = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        botdead = new javax.swing.JButton();
        jogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ptsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ptsair.png"))); // NOI18N
        getContentPane().add(ptsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        biblio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bibliounder.png"))); // NOI18N
        getContentPane().add(biblio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        biblio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bibliocup.png"))); // NOI18N
        getContentPane().add(biblio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        biblio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/biblioamong.png"))); // NOI18N
        getContentPane().add(biblio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        biblio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bibliodead.png"))); // NOI18N
        getContentPane().add(biblio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        redimensionar.setText("jButton1");
        redimensionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redimensionarActionPerformed(evt);
            }
        });
        getContentPane().add(redimensionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1233, 0, 20, 20));

        ptfechar.setText("jButton1");
        ptfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptfecharActionPerformed(evt);
            }
        });
        getContentPane().add(ptfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 20, 20));

        minimizar.setText("jButton1");
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 20, 20));

        sim.setText("jButton1");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });
        getContentPane().add(sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 40, 20));

        nao.setText("jButton1");
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });
        getContentPane().add(nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 40, 20));

        botunder.setText("jButton1");
        botunder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botunderActionPerformed(evt);
            }
        });
        getContentPane().add(botunder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 70));

        botcup.setText("jButton1");
        botcup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botcupActionPerformed(evt);
            }
        });
        getContentPane().add(botcup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 290, 60));

        botamong.setText("jButton1");
        botamong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botamongActionPerformed(evt);
            }
        });
        getContentPane().add(botamong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 290, 60));

        voltar.setText("jButton1");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, -1));

        botdead.setText("jButton1");
        botdead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botdeadActionPerformed(evt);
            }
        });
        getContentPane().add(botdead, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 270, 50));

        jogar.setText("jButton1");
        jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarActionPerformed(evt);
            }
        });
        getContentPane().add(jogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 358, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redimensionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redimensionarActionPerformed

    }//GEN-LAST:event_redimensionarActionPerformed

    private void ptfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptfecharActionPerformed
        ptsair.setVisible(true);
        sim.setVisible(true);
        nao.setVisible(true);
    }//GEN-LAST:event_ptfecharActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        this.setState (JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
        System.exit(0);
    }//GEN-LAST:event_simActionPerformed

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
        ptsair.setVisible(false);
        //ingsair.setVisible(false);
        sim.setVisible(false);
        nao.setVisible(false);
    }//GEN-LAST:event_naoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       biblio2.setVisible(false);
       biblio3.setVisible(false);
        ptsair.setVisible(false);
       sim.setVisible(false);
       nao.setVisible(false);
       System.out.println("\n\n\n\n\n\n\n\n\n\n\n");
      System.out.println("Usuario criado: "+entrada);
       System.out.println("Mensagem do suporte: "+supo);
       System.out.println("Usuários pré criados: "+listaUsu);
       
    }//GEN-LAST:event_formWindowOpened

    private void botunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botunderActionPerformed
      biblio1.setVisible(true);
      biblio2.setVisible(false);
      biblio3.setVisible(false);
      biblio4.setVisible(false);
    }//GEN-LAST:event_botunderActionPerformed

    private void botcupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botcupActionPerformed
        biblio1.setVisible(false);
        biblio2.setVisible(true);
        biblio3.setVisible(false);
        biblio4.setVisible(false);
    }//GEN-LAST:event_botcupActionPerformed

    private void botamongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botamongActionPerformed
        biblio1.setVisible(false);
        biblio2.setVisible(false);
        biblio3.setVisible(true);
        biblio4.setVisible(false);
    }//GEN-LAST:event_botamongActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        loja lj = new loja(listaUsu, entrada, supo);
                    lj.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void botdeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botdeadActionPerformed
       biblio1.setVisible(false);
        biblio2.setVisible(false);
        biblio3.setVisible(false);
        biblio4.setVisible(true);
    }//GEN-LAST:event_botdeadActionPerformed

    private void jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarActionPerformed
    try {
        Process po = Runtime.getRuntime().exec("C:/Users/danie/OneDrive/Documentos/My Games/Undertale v1.001/UNDERTALE.exe");
    } catch (IOException ex) {
        Logger.getLogger(biblioteca.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jogarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biblio1;
    private javax.swing.JLabel biblio2;
    private javax.swing.JLabel biblio3;
    private javax.swing.JLabel biblio4;
    private javax.swing.JButton botamong;
    private javax.swing.JButton botcup;
    private javax.swing.JButton botdead;
    private javax.swing.JButton botunder;
    private javax.swing.JButton jogar;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton nao;
    private javax.swing.JButton ptfechar;
    private javax.swing.JLabel ptsair;
    private javax.swing.JButton redimensionar;
    private javax.swing.JButton sim;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
