/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

import controlador.Usuario;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author danie
 */
public class deadcompr extends javax.swing.JFrame {
List<Usuario> listaUsu = new ArrayList<>();
   List<String> entrada = new ArrayList<>();
   List<String> supo = new ArrayList<>();
   
    /**
     * Creates new form deadcompr
     */
    public deadcompr() {
        initComponents();
    }
public deadcompr(List<Usuario> listaUsu, List<String> entrada, List<String> supo) {
        initComponents();
        
        this.listaUsu = listaUsu;
         this.entrada = entrada;
         this.supo = supo;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        confir = new javax.swing.JLabel();
        finalz = new javax.swing.JLabel();
        deadimg = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        pedido = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        finalizarbot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 236, 20, -1));

        jRadioButton2.setBackground(new java.awt.Color(42, 42, 42));
        jRadioButton2.setForeground(new java.awt.Color(42, 42, 42));
        jRadioButton2.setText("jRadioButton1");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 134, 20, -1));

        jRadioButton3.setText("jRadioButton1");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 335, 20, -1));

        jRadioButton4.setText("jRadioButton1");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 537, 20, -1));

        jRadioButton5.setText("jRadioButton1");
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 437, 20, -1));

        confir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/obrigado.png"))); // NOI18N
        getContentPane().add(confir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        finalz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirdead.png"))); // NOI18N
        getContentPane().add(finalz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        deadimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compradead.png"))); // NOI18N
        getContentPane().add(deadimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        voltar.setText("jButton1");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 38, 30, 20));

        pedido.setText("jButton1");
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        getContentPane().add(pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 360, 60));

        fechar.setText("jButton1");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });
        getContentPane().add(fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 202, 30, -1));

        finalizarbot.setText("jButton1");
        finalizarbot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarbotActionPerformed(evt);
            }
        });
        getContentPane().add(finalizarbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 610, 360, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       confir.setVisible(false);
       fechar.setVisible(false);
       finalz.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        loja lj = new loja(listaUsu, entrada, supo);
        lj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
        finalz.setVisible(true);
       fechar.setVisible(true);
       jRadioButton1.setVisible(false);
       jRadioButton2.setVisible(false);
       jRadioButton3.setVisible(false);
       jRadioButton4.setVisible(false);
       jRadioButton5.setVisible(false);
       pedido.setVisible(false);
       finalizarbot.setVisible(true);
    }//GEN-LAST:event_pedidoActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
       loja lj = new loja(listaUsu, entrada, supo);
        lj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fecharActionPerformed

    private void finalizarbotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarbotActionPerformed
        finalizarbot.setVisible(false);
        confir.setVisible(true);
    }//GEN-LAST:event_finalizarbotActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confir;
    private javax.swing.JLabel deadimg;
    private javax.swing.JButton fechar;
    private javax.swing.JButton finalizarbot;
    private javax.swing.JLabel finalz;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JButton pedido;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
