/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

import controlador.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author danie
 */
public class loja extends javax.swing.JFrame {

   List<Usuario> listaUsu = new ArrayList<>();
   List<String> entrada = new ArrayList<>();
   List<String> supo = new ArrayList<>();
    public loja() {
        initComponents();
    }
    public loja(List<Usuario> listaUsu, List<String> entrada, List<String> supo) {
        initComponents();
        
        this.listaUsu = listaUsu;
         this.entrada = entrada;
         this.supo = supo;
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecalho = new javax.swing.JLabel();
        ptsair = new javax.swing.JLabel();
        ptfechar = new javax.swing.JButton();
        redimensionar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        nao = new javax.swing.JButton();
        sim = new javax.swing.JButton();
        Scroll = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        amigs = new javax.swing.JLabel();
        notf = new javax.swing.JLabel();
        sevira = new javax.swing.JLabel();
        ajudinha = new javax.swing.JLabel();
        notifi = new javax.swing.JLabel();
        biblioteca = new javax.swing.JButton();
        suporte = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        opcao = new javax.swing.JLabel();
        opcao2 = new javax.swing.JLabel();
        Scroll1 = new javax.swing.JScrollPane();
        areatextsup = new javax.swing.JTextArea();
        sup = new javax.swing.JLabel();
        pesquisa = new javax.swing.JTextField();
        loja1 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        config = new javax.swing.JButton();
        discord = new javax.swing.JButton();
        youtube = new javax.swing.JButton();
        btconfig = new javax.swing.JButton();
        under = new javax.swing.JButton();
        dead = new javax.swing.JButton();
        comprardead = new javax.swing.JButton();
        comprarunder = new javax.swing.JButton();
        amigos = new javax.swing.JButton();
        fech = new javax.swing.JButton();
        perfil2 = new javax.swing.JButton();
        perfil3 = new javax.swing.JButton();
        ajuda = new javax.swing.JButton();
        perfil = new javax.swing.JButton();
        notif = new javax.swing.JButton();
        perf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabecalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ptloja1.png"))); // NOI18N
        getContentPane().add(cabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ptsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ptsair.png"))); // NOI18N
        getContentPane().add(ptsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        ptfechar.setText("jButton1");
        ptfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptfecharActionPerformed(evt);
            }
        });
        getContentPane().add(ptfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 20, 20));

        redimensionar.setText("jButton1");
        redimensionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redimensionarActionPerformed(evt);
            }
        });
        getContentPane().add(redimensionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1233, 0, 20, 20));

        minimizar.setText("jButton1");
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 0, 20, 20));

        nao.setText("jButton1");
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });
        getContentPane().add(nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 40, 20));

        sim.setText("jButton1");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });
        getContentPane().add(sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 40, 20));

        Scroll.setBackground(new java.awt.Color(0, 0, 0));
        Scroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Scroll.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amigs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/social.png"))); // NOI18N
        jPanel2.add(amigs, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, -1, -1));

        notf.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        notf.setForeground(new java.awt.Color(255, 255, 255));
        notf.setText("Não há notificações");
        jPanel2.add(notf, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 35, -1, -1));

        sevira.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        sevira.setForeground(new java.awt.Color(255, 255, 255));
        sevira.setText("SE VIRA");
        jPanel2.add(sevira, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, -1, -1));

        ajudinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notifi.png"))); // NOI18N
        ajudinha.setText("jLabel1");
        jPanel2.add(ajudinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        notifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notifi.png"))); // NOI18N
        jPanel2.add(notifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, -1));

        biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btbiblio.png"))); // NOI18N
        biblioteca.setBorder(null);
        biblioteca.setBorderPainted(false);
        biblioteca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        biblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bibliotecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bibliotecaMouseExited(evt);
            }
        });
        biblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaActionPerformed(evt);
            }
        });
        jPanel2.add(biblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, 50));

        suporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sup1.png"))); // NOI18N
        suporte.setText("jButton1");
        suporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suporteMouseExited(evt);
            }
        });
        jPanel2.add(suporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 130, 170, 50));

        enviar.setBackground(new java.awt.Color(0, 0, 0));
        enviar.setForeground(new java.awt.Color(255, 255, 255));
        enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enviar.png"))); // NOI18N
        enviar.setText("jButton1");
        enviar.setBorder(null);
        enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enviarMouseExited(evt);
            }
        });
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        jPanel2.add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 130, 35));

        opcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opcao1.png"))); // NOI18N
        opcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opcaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opcaoMouseExited(evt);
            }
        });
        jPanel2.add(opcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 10, -1, -1));

        opcao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/opcao2.png"))); // NOI18N
        opcao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opcao2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opcao2MouseExited(evt);
            }
        });
        jPanel2.add(opcao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 70, 200, -1));

        Scroll1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Scroll1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Scroll1MouseExited(evt);
            }
        });

        areatextsup.setColumns(20);
        areatextsup.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        areatextsup.setRows(5);
        areatextsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                areatextsupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                areatextsupMouseExited(evt);
            }
        });
        Scroll1.setViewportView(areatextsup);

        jPanel2.add(Scroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 400, 210));

        sup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sup.png"))); // NOI18N
        sup.setText("jLabel1");
        sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supMouseExited(evt);
            }
        });
        jPanel2.add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 90, 480, -1));

        pesquisa.setFont(new java.awt.Font("Yu Gothic Medium", 1, 16)); // NOI18N
        pesquisa.setText("Pesquise por games....");
        pesquisa.setBorder(null);
        pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaMouseClicked(evt);
            }
        });
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        jPanel2.add(pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 98, 760, 50));

        loja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loja.png"))); // NOI18N
        jPanel2.add(loja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menu.setText("jButton1");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        jPanel2.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        config.setText("jButton1");
        config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configMouseExited(evt);
            }
        });
        jPanel2.add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 47, 40));

        discord.setText("jButton1");
        discord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discordActionPerformed(evt);
            }
        });
        jPanel2.add(discord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 40, 30));

        youtube.setText("jButton1");
        youtube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youtubeActionPerformed(evt);
            }
        });
        jPanel2.add(youtube, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 40, 30));

        btconfig.setText("jButton1");
        jPanel2.add(btconfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 70, 177, 50));

        under.setText("jButton1");
        under.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underActionPerformed(evt);
            }
        });
        jPanel2.add(under, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 340, 360, 180));

        dead.setText("jButton1");
        dead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadActionPerformed(evt);
            }
        });
        jPanel2.add(dead, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 340, 360, 180));

        comprardead.setText("jButton1");
        comprardead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprardeadActionPerformed(evt);
            }
        });
        jPanel2.add(comprardead, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 160, 50));

        comprarunder.setText("jButton1");
        comprarunder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarunderActionPerformed(evt);
            }
        });
        jPanel2.add(comprarunder, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 160, 50));

        amigos.setText("jButton1");
        amigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amigosActionPerformed(evt);
            }
        });
        jPanel2.add(amigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 588, 110, 30));

        fech.setText("jButton1");
        fech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechActionPerformed(evt);
            }
        });
        jPanel2.add(fech, new org.netbeans.lib.awtextra.AbsoluteConstraints(1253, 80, 10, 20));

        perfil2.setText("jButton1");
        perfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil2ActionPerformed(evt);
            }
        });
        jPanel2.add(perfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 190, 30));

        perfil3.setText("jButton1");
        perfil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil3ActionPerformed(evt);
            }
        });
        jPanel2.add(perfil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 120, 110));

        Scroll.setViewportView(jPanel2);

        getContentPane().add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1280, 660));

        ajuda.setText("jButton1");
        ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajudaMouseExited(evt);
            }
        });
        ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaActionPerformed(evt);
            }
        });
        getContentPane().add(ajuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1153, 30, 20, 20));

        perfil.setText("jButton1");
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        getContentPane().add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 30, 90, 20));

        notif.setText("jButton1");
        notif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notifMouseExited(evt);
            }
        });
        notif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifActionPerformed(evt);
            }
        });
        getContentPane().add(notif, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 30, 20, 20));

        perf.setText("jButton1");
        perf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfActionPerformed(evt);
            }
        });
        getContentPane().add(perf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 25, 100, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ptfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptfecharActionPerformed
        ptsair.setVisible(true);
        sim.setVisible(true);
        nao.setVisible(true);
    }//GEN-LAST:event_ptfecharActionPerformed

    private void redimensionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redimensionarActionPerformed

    }//GEN-LAST:event_redimensionarActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        this.setState (JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
        ptsair.setVisible(false);
        
        sim.setVisible(false);
        nao.setVisible(false);
    }//GEN-LAST:event_naoActionPerformed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
        this.dispose();
    }//GEN-LAST:event_simActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaActionPerformed

    private void pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaMouseClicked
       pesquisa.setText("");
    }//GEN-LAST:event_pesquisaMouseClicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
       opcao.setVisible(true);
        biblioteca.setVisible(true);
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
       opcao.setVisible(false);
        biblioteca.setVisible(false);
    }//GEN-LAST:event_menuMouseExited

    private void configMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseEntered
        opcao2.setVisible(true);
        suporte.setVisible(true);
    }//GEN-LAST:event_configMouseEntered

    private void configMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseExited
       opcao2.setVisible(false);
       suporte.setVisible(true);
       suporte.setVisible(false);
    }//GEN-LAST:event_configMouseExited

    private void opcaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcaoMouseEntered
        opcao.setVisible(true);
        biblioteca.setVisible(true);
    }//GEN-LAST:event_opcaoMouseEntered

    private void opcaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcaoMouseExited
        opcao.setVisible(false);
        biblioteca.setVisible(false);
    }//GEN-LAST:event_opcaoMouseExited

    private void opcao2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcao2MouseEntered
      opcao2.setVisible(true);
      btconfig.setVisible(true);
      suporte.setVisible(true);
       
        
    }//GEN-LAST:event_opcao2MouseEntered

    private void opcao2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcao2MouseExited
        opcao2.setVisible(false);
        btconfig.setVisible(false);
        suporte.setVisible(false);
        opcao2.setVisible(false);
        enviar.setVisible(false);
        areatextsup.setVisible(false);
        sup.setVisible(false);
        Scroll1.setVisible(false);
         suporte.setVisible(false);
    }//GEN-LAST:event_opcao2MouseExited

    private void bibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaActionPerformed
        biblioteca bi = new biblioteca(listaUsu, entrada, supo);
                    bi.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_bibliotecaActionPerformed

    private void bibliotecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMouseEntered
        opcao.setVisible(true);
        biblioteca.setVisible(true);
    }//GEN-LAST:event_bibliotecaMouseEntered

    private void bibliotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaMouseExited
       opcao.setVisible(false);
        biblioteca.setVisible(false);
    }//GEN-LAST:event_bibliotecaMouseExited

    private void discordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discordActionPerformed
       try{
        URI link = new URI("https://discord.gg/nH4rcHkF7j");
        Desktop.getDesktop().browse(link);
    }catch(Exception erro){
            System.out.println(erro);
    }
    }//GEN-LAST:event_discordActionPerformed

    private void youtubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youtubeActionPerformed
         try{
        URI link = new URI("https://www.youtube.com/channel/UCXdAcABy20M6HDppWQYAD5w?view_as=subscriber");
        Desktop.getDesktop().browse(link);
    }catch(Exception erro){
            System.out.println(erro);
    }
    }//GEN-LAST:event_youtubeActionPerformed

    private void suporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suporteMouseEntered
        opcao2.setVisible(true);
        config.setVisible(true);
        areatextsup.setVisible(true);
        sup.setVisible(true);
        Scroll1.setVisible(true);
         suporte.setVisible(true);
         enviar.setVisible(true);
    }//GEN-LAST:event_suporteMouseEntered

    private void suporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suporteMouseExited
        opcao2.setVisible(false);
        areatextsup.setVisible(false);
        sup.setVisible(false);
        Scroll1.setVisible(false);
         suporte.setVisible(false);
         enviar.setVisible(false);
    }//GEN-LAST:event_suporteMouseExited

    private void supMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMouseEntered
       opcao2.setVisible(true);
        config.setVisible(true);
        areatextsup.setVisible(true);
        sup.setVisible(true);
        Scroll1.setVisible(true);
         suporte.setVisible(true);
         enviar.setVisible(true);
    }//GEN-LAST:event_supMouseEntered

    private void supMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMouseExited
        opcao2.setVisible(false);
        areatextsup.setVisible(false);
        sup.setVisible(false);
        Scroll1.setVisible(false);
         suporte.setVisible(false);
         enviar.setVisible(false);
    }//GEN-LAST:event_supMouseExited

    private void enviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarMouseEntered
         opcao2.setVisible(true);
        config.setVisible(true);
        areatextsup.setVisible(true);
        sup.setVisible(true);
        Scroll1.setVisible(true);
         suporte.setVisible(true);
         enviar.setVisible(true);
    }//GEN-LAST:event_enviarMouseEntered

    private void enviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarMouseExited
        opcao2.setVisible(false); 
        areatextsup.setVisible(false);
        sup.setVisible(false);
        Scroll1.setVisible(false);
         suporte.setVisible(false);
         enviar.setVisible(false);
    }//GEN-LAST:event_enviarMouseExited

    private void areatextsupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areatextsupMouseEntered
       opcao2.setVisible(true);
        config.setVisible(true);
        areatextsup.setVisible(true);
        sup.setVisible(true);
        Scroll1.setVisible(true);
         suporte.setVisible(true);
          enviar.setVisible(true);
    }//GEN-LAST:event_areatextsupMouseEntered

    private void areatextsupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areatextsupMouseExited
      opcao2.setVisible(false); 
        areatextsup.setVisible(false);
        sup.setVisible(false);
        Scroll1.setVisible(false);
         suporte.setVisible(false);
          enviar.setVisible(false);
    }//GEN-LAST:event_areatextsupMouseExited

    private void Scroll1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Scroll1MouseEntered
        opcao2.setVisible(true);
        config.setVisible(true);
        areatextsup.setVisible(true);
        sup.setVisible(true);
        Scroll1.setVisible(true);
         suporte.setVisible(true);
          enviar.setVisible(true);
    }//GEN-LAST:event_Scroll1MouseEntered

    private void Scroll1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Scroll1MouseExited
         opcao2.setVisible(false); 
        areatextsup.setVisible(false);
        sup.setVisible(false);
        Scroll1.setVisible(false);
         suporte.setVisible(false);
          enviar.setVisible(false);
    }//GEN-LAST:event_Scroll1MouseExited

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
       
        supo.add(areatextsup.getText());
        
        areatextsup.setText("");
        System.out.println("\n\n\n\n\n\n\n\n\n\n\n");
      System.out.println("Usuario criado: "+entrada);
       System.out.println("Mensagem do suporte: "+supo);
       System.out.println("Usuários pré criados: "+listaUsu);
    }//GEN-LAST:event_enviarActionPerformed

    private void ajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaActionPerformed
        ajudinha.setVisible(true);
        sevira.setVisible(true);
    }//GEN-LAST:event_ajudaActionPerformed

    private void ajudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajudaMouseExited
        ajudinha.setVisible(false);
        sevira.setVisible(false);
    }//GEN-LAST:event_ajudaMouseExited

    private void underActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underActionPerformed
        undertale ut = new undertale(listaUsu, entrada, supo);
                    ut.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_underActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         ptsair.setVisible(false);
       sim.setVisible(false);
       nao.setVisible(false);
       pesquisa.setBackground(new java.awt.Color(0,0,0,1));
        biblioteca.setBackground(new java.awt.Color(0,0,0,1));
         biblioteca.setForeground(new java.awt.Color(0,0,0,1));
       opcao.setVisible(false);
       opcao2.setVisible(false);
       biblioteca.setVisible(false);
        areatextsup.setVisible(false);
        sup.setVisible(false);
        Scroll1.setVisible(false);
        suporte.setVisible(false);
        enviar.setVisible(false);
        ajudinha.setVisible(false);
        sevira.setVisible(false);
        amigs.setVisible(false);
         notf.setVisible(false);
          notifi.setVisible(false);
          perfil2.setVisible(false);
          perfil3.setVisible(false);

          try
   {
       String os = System.getProperty("os.name");

       if (os.contains("Windows"))
       {
           Runtime.getRuntime().exec("cls");
       }
       else
       {
           Runtime.getRuntime().exec("clear");
       }
   }
   catch (Exception exception)
   {
       //  Handle exception.
   }
          System.out.println("\n\n\n\n\n\n\n\n\n\n\n");
        System.out.println("Usuario criado: "+entrada);
       System.out.println("Mensagem do suporte: "+supo);
       System.out.println("Usuários pré criados: "+listaUsu);
       
    }//GEN-LAST:event_formWindowOpened

    private void deadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadActionPerformed
        deadcell dc = new deadcell(listaUsu, entrada, supo);
                    dc.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_deadActionPerformed

    private void comprardeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprardeadActionPerformed
      deadcompr dcr = new deadcompr(listaUsu, entrada, supo);
                    dcr.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_comprardeadActionPerformed

    private void comprarunderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarunderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprarunderActionPerformed

    private void notifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notifMouseExited
        notf.setVisible(false);
        notifi.setVisible(false);
    }//GEN-LAST:event_notifMouseExited

    private void notifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifActionPerformed
       notf.setVisible(true);
        notifi.setVisible(true);
    }//GEN-LAST:event_notifActionPerformed

    private void amigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amigosActionPerformed
       amigs.setVisible(true);
       perfil2.setVisible(true);
          perfil3.setVisible(true);
    }//GEN-LAST:event_amigosActionPerformed

    private void fechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechActionPerformed
         amigs.setVisible(false);
         perfil2.setVisible(false);
         perfil3.setVisible(false);
    }//GEN-LAST:event_fechActionPerformed

    private void perfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfActionPerformed

    }//GEN-LAST:event_perfActionPerformed

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        perfil per = new perfil(listaUsu, entrada, supo);
                    per.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_perfilActionPerformed

    private void perfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil2ActionPerformed
       perfil per = new perfil(listaUsu, entrada, supo);
                    per.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_perfil2ActionPerformed

    private void perfil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil3ActionPerformed
         perfil per = new perfil(listaUsu, entrada, supo);
                    per.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_perfil3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JScrollPane Scroll1;
    private javax.swing.JButton ajuda;
    private javax.swing.JLabel ajudinha;
    private javax.swing.JButton amigos;
    private javax.swing.JLabel amigs;
    private javax.swing.JTextArea areatextsup;
    private javax.swing.JButton biblioteca;
    private javax.swing.JButton btconfig;
    private javax.swing.JLabel cabecalho;
    private javax.swing.JButton comprardead;
    private javax.swing.JButton comprarunder;
    private javax.swing.JButton config;
    private javax.swing.JButton dead;
    private javax.swing.JButton discord;
    private javax.swing.JButton enviar;
    private javax.swing.JButton fech;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loja1;
    private javax.swing.JButton menu;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton nao;
    private javax.swing.JLabel notf;
    private javax.swing.JButton notif;
    private javax.swing.JLabel notifi;
    private javax.swing.JLabel opcao;
    private javax.swing.JLabel opcao2;
    private javax.swing.JButton perf;
    private javax.swing.JButton perfil;
    private javax.swing.JButton perfil2;
    private javax.swing.JButton perfil3;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JButton ptfechar;
    private javax.swing.JLabel ptsair;
    private javax.swing.JButton redimensionar;
    private javax.swing.JLabel sevira;
    private javax.swing.JButton sim;
    private javax.swing.JLabel sup;
    private javax.swing.JButton suporte;
    private javax.swing.JButton under;
    private javax.swing.JButton youtube;
    // End of variables declaration//GEN-END:variables
}
