/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

import controlador.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author danie
 */
public class undertale extends javax.swing.JFrame {
List<Usuario> listaUsu = new ArrayList<>();
   List<String> entrada = new ArrayList<>();
   List<String> supo = new ArrayList<>();
    /**
     * Creates new form undertale
     */
    public undertale() {
        initComponents();
        
    }
public undertale(List<Usuario> listaUsu, List<String> entrada, List<String> supo) {
        initComponents();
        
        this.listaUsu = listaUsu;
         this.entrada = entrada;
         this.supo = supo;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ptsair = new javax.swing.JLabel();
        under = new javax.swing.JLabel();
        nao = new javax.swing.JButton();
        sim = new javax.swing.JButton();
        redimensionar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        ptfechar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 680));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ptsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ptsair.png"))); // NOI18N
        getContentPane().add(ptsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        under.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/undertale.png"))); // NOI18N
        getContentPane().add(under, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 680));

        nao.setText("jButton1");
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });
        getContentPane().add(nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 40, 20));

        sim.setText("jButton1");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });
        getContentPane().add(sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 40, 20));

        redimensionar.setText("jButton1");
        redimensionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redimensionarActionPerformed(evt);
            }
        });
        getContentPane().add(redimensionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 20, 20));

        minimizar.setText("jButton1");
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 20, 20));

        ptfechar.setText("jButton1");
        ptfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptfecharActionPerformed(evt);
            }
        });
        getContentPane().add(ptfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 20, 20));

        voltar.setText("jButton1");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redimensionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redimensionarActionPerformed

    }//GEN-LAST:event_redimensionarActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        this.setState (JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed

    private void ptfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptfecharActionPerformed
        ptsair.setVisible(true);
        sim.setVisible(true);
        nao.setVisible(true);
    }//GEN-LAST:event_ptfecharActionPerformed

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
        ptsair.setVisible(false);

        sim.setVisible(false);
        nao.setVisible(false);
    }//GEN-LAST:event_naoActionPerformed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
        this.dispose();
    }//GEN-LAST:event_simActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
       loja lj = new loja(listaUsu, entrada, supo);
                    lj.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ptsair.setVisible(false);
       sim.setVisible(false);
       nao.setVisible(false);
       
        System.out.println("Usuario criado: "+entrada);
       System.out.println("Mensagem do suporte: "+supo);
       System.out.println("Usuários pré criados: "+listaUsu);
       System.out.println("--------------- 4");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton minimizar;
    private javax.swing.JButton nao;
    private javax.swing.JButton ptfechar;
    private javax.swing.JLabel ptsair;
    private javax.swing.JButton redimensionar;
    private javax.swing.JButton sim;
    private javax.swing.JLabel under;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
